### ISSUE TITLE
Publishing Error

### ISSUE THREAD

**Issue by phillip-toone** [senaite/senaite.impress#49]
When I attempt to publish results I get this error:
![publisherror](https://user-images.githubusercontent.com/5975365/47575798-1f1cab00-d900-11e8-9295-cf703bda3f60.png)

**Comment by ramonski** [comment]
Thanks @phillip-toone. Can you also please provide a screenshot of the AR `BK-0002-R01` and if possible the Traceback of the log file

**Comment by phillip-toone** [comment]
This is as much as I can fit on one screen for a screenshot. Let me know if you need me to scroll down and take another.  Also, there is an attachment to this analysis request that is now shown.
![bk-0002-r01](https://user-images.githubusercontent.com/5975365/47576975-02ce3d80-d903-11e8-89cb-30b3cfc7c611.png)
Do I need to set up a AR Template in the LIMS Configuration?

**Comment by ramonski** [comment]
What kind of attachment is this? Does it work when you set the attachment to "ignore in report"?
Regarding the Traceback, look into `/home/senaite/data/senaitelims/client{1,2}/event.log`

**Comment by phillip-toone** [comment]
Changing the attachment to "ignore in report" doesn't effect this error.  I also tried this on a different analysis request `CT-0001-R01` without an attachment and I get the same error:
![ct-0001-r01](https://user-images.githubusercontent.com/5975365/47578831-a7527e80-d907-11e8-8fc5-8cd4bc03197c.png)

**Comment by ramonski** [comment]
Probably related with https://github.com/senaite/senaite.core/pull/1064
Which version of WeasyPrint do you have?

You might need to pin it to version `0.42.3`

**Comment by phillip-toone** [comment]
I installed WeasyPrint  with the following commands
```
apt install -y build-essential python3-dev python3-pip python3-cffi libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info
pip install WeasyPrint
```
But I get the same error when I attempt to publish results.

**Comment by ramonski** [comment]
`WeasyPrint? is not installed by the system package manager, it is an internal dependency of `senaite.core`: https://github.com/senaite/senaite.core/blob/master/setup.py#L53
Therefore, you must pin it in your `buildout.cfg` to  `WeasyPrint=0.42.3` in your `[versions]` section and re-run `bin/buildout -c live.cfg` as user `senaite`.

**Comment by phillip-toone** [comment]
Where is the file buildout.cfg located what I need to modify?  I see it in a number of different locations:
```
/home/senaite/senaitelims/src/senaite.core/buildout.cfg
/home/senaite/senaitelims/src/senaite.impress/buildout.cfg
/home/senaite/senaitelims/src/senaite.lims/buildout.cfg
/root/Plone-4.3.6-UnifiedInstaller/buildout_templates/buildout.cfg
/usr/local/Plone/zinstance/buildout.cfg
```
And where do I runt this command `bin/buildout -c live.cfg`.   I get this error message.
```
-bash: bin/buildout: No such file or directory
```

**Comment by ramonski** [comment]
The buildout config from the playbook is located here:

`/home/senaite/senaitelims/live.cfg`

This is also the location where you run `bin/buildout`, e.g.:

```
sudo su - senaite
cd /home/senaite/senaitelims
bin/buildout -c live.cfg
```

However, we merged https://github.com/senaite/senaite.core/pull/1064 and updating the `senaite.core` source should do it:

```
sudo su - senaite
cd /home/senaite/senaitelims/src/senaite.lims
git pull
cd /home/senaite/senaitelims/src/
bin/buildout -c live.cfg
```

Then log-in as root and do the following:

```
supervisorctl restart all
```

**Comment by phillip-toone** [comment]
It looks like I am now able to produce pdf documents. Thank you. But when I attempt to email the results I get the following error.
![email-failed](https://user-images.githubusercontent.com/5975365/47789259-bc4d5a00-dcd9-11e8-8e5a-25be4c8dc411.png)
I assume this is because I do not have this evaluation system set up to properly send emails.  But I do see that when I have made multiple attempt to publish and save the results, each attempt is saved.
![analysisreports](https://user-images.githubusercontent.com/5975365/47789409-13ebc580-dcda-11e8-9415-760f224be55e.png)
Also, I see that in my list if analysis requests that this is listed as "verified" but not "published" even thought the results have been "published" into a saved pdf.
![analysisrequests](https://user-images.githubusercontent.com/5975365/47789597-970d1b80-dcda-11e8-8647-99cc2ef37e51.png)
Is there a way to make an analysis request be published for a system without a mail server?
![analysisrequestssummary](https://user-images.githubusercontent.com/5975365/47789678-ce7bc800-dcda-11e8-91f4-30c93b9f632f.png)

**Comment by ramonski** [comment]
Hi @phillip-toone, Analysis Requests transition to published only if the email with the report was successfully sent to the client, otherwise it stays in the previous state. There is only no built-in way to force publish an AR without sending the email.

I'm closing this issue, because the Code works as expected.

**Comment by phillip-toone** [comment]
Thank you again for all of your help. :)

**Comment by grulisco** [comment]
Hi @phillip-toone and @ramonski, in **our test-instance** ARs get into published state, when at least one of the responsibles (department managers with e-mail-adress) is mentioned in impress.
The client does not necessarily needs to be e-mailed.

**Comment by phillip-toone** [comment]
@grulisco What does it mean to be "mentioned"? Does this require a working email server to send an email to a valid email address? What if a client wants the results physically mailed to them instead of an email?

**Comment by grulisco** [comment]
@phillip-toone Sorry for my bad english... 
Look at the impress e-mail view:
![grafik](https://user-images.githubusercontent.com/25460329/47813330-0ae70c80-dd4b-11e8-9691-6671451a9c3e.png)
In this example client contact is blue (means it has a valid e-mail-adress configured), but you can untick, if you don't want to send the e-mail to him.
The responsibles (at this stage of impress: department managers) are set as CC. Blue also shows that the responsible lab contacts (=me) has a valid e-mail adress.
When the e-mail is sent successfully from senaite/plone at least to **me** or any single valid e-mail recipient the AR is set to published state, finally.
Of course you need to:
- configure E-Mail properly in plone setup
- configure lab contact with valid e-mail and assign to lab department
- assign analysis services to lab department
in advance.
HTH
