### ISSUE TITLE
Revise concept of primary sample in multi-reports

### ISSUE THREAD

**Issue by grulisco** [senaite/senaite.impress#58]
Publishing several samples/requests into a single multireport is using one of them as the primary one to:
- displaying common information in the report header, although some might differ in detail (e.g.client contact, batch info).
- determining the location of the saved report (if not saved individually)

The word **primary** implies a kind of **first** of something, so it is confusing for users to recognize the actual primary request, because of contradicting expectations:
- In publish view the list of samples is determined by the current sort order of the calling sample view, which can vary by user task. So the **first entry is highly at random**.
- In the multireport header adress, contact, batch information are  based on the **oldest** sample, samples are sorted ascending by date (which is a good default behaviour IMO).
- The pdf of the multireport is saved to the **latest** sample (changed newly, see #52), so you won't find it easily again having one of the other ways in mind.

So I propose to make this work in a more consistent and user-friendly way.

IMHO the **first** sample in the sample list (preferably in ascending order) should be considered as the **primary** one and should receive the saved pdf too.

**Comment by ramonski** [comment]
I think this one can be closed with having the Storage Adapter in place which was introduced here: https://github.com/senaite/senaite.impress/pull/71
