### ISSUE TITLE
Attachment not showing in report althought Render in Report is selected 

### ISSUE THREAD

**Issue by garciagab** [senaite/senaite.impress#61]
Attach a report to AR

Publish report 

No attachment attached to publish report report 

Report status is verified 

![image](https://user-images.githubusercontent.com/42850389/52483489-703c6c00-2b8a-11e9-933b-4ff0fc6b38a3.png)

**Comment by garciagab** [comment]
Selected two AR to publish, they both show up and i can view both report, however only one report is displayed in the email list 

![image](https://user-images.githubusercontent.com/42850389/52720308-bd02b700-2f7d-11e9-8b95-409bcb93e4c2.png)

![image](https://user-images.githubusercontent.com/42850389/52719969-1c13fc00-2f7d-11e9-9249-432c4638dcb4.png)

**Comment by garciagab** [comment]
![image](https://user-images.githubusercontent.com/42850389/52720357-d99eef00-2f7d-11e9-9c59-12fac825fc43.png)

**Comment by ramonski** [comment]
Hi @garciagab, you are trying to render a PDF in the PDF Report, which is not possible.
Only images, e.g. files with the extensions `.gif`, `.jpg`, `.png`, will show up in the report when the report option "Render in report" is selected.

**Comment by garciagab** [comment]
We are publishing reports 
Steps 
Select AR to be published 
![image](https://user-images.githubusercontent.com/42850389/52722143-6c8d5880-2f81-11e9-9311-7dc7191b2c2b.png)
Select Publish the following screen comes up 

![image](https://user-images.githubusercontent.com/42850389/52722418-f0474500-2f81-11e9-913f-04fe5632c225.png)

Select email 

![image](https://user-images.githubusercontent.com/42850389/52722535-2e446900-2f82-11e9-9d82-6a3c84f5cb03.png)

Report attached


![image](https://user-images.githubusercontent.com/42850389/52722606-592ebd00-2f82-11e9-9413-a4cc2329feb7.png)

Problem only one PDF report is attached.

![image](https://user-images.githubusercontent.com/42850389/52722719-95fab400-2f82-11e9-91a7-287d37439f40.png)

**Comment by garciagab** [comment]
If I go to overview 

![image](https://user-images.githubusercontent.com/42850389/52723897-baf02680-2f84-11e9-9005-2205d2d3cde0.png)


![image](https://user-images.githubusercontent.com/42850389/52723728-6cdb2300-2f84-11e9-82f6-5d1ba87e62a5.png)
 and click on email 

![image](https://user-images.githubusercontent.com/42850389/52723810-95fbb380-2f84-11e9-9e9a-cc86cad66a14.png)

All the reports are attached

**Comment by ramonski** [comment]
Hi @garciagab, I'm going to close this issue because of the reasoning commented here: https://github.com/senaite/senaite.impress/issues/61#issuecomment-463236956
You can only render Images in JPG/PNG/BMP format directly in the report. All other formats can be attached to the report email (like in your case the PDF)
